Expense/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'expense'

urlpatterns = [
    path('expense', login_required(views.Home), name='home'),

    path('expense/add/', login_required(views.Add), name='add'),

    path('expense/edit/<int:pk>', login_required(views.Edit), name='edit'),

    path('expense/delete', login_required(views.Delete), name='delete'),

    path('expense/type/add', login_required(views.expense_type_add), name='type-add'),

]

Inventory/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'inventory'

urlpatterns = [
    path('inventory', login_required(views.Home), name='home'),

    path('inventory/add/', login_required(views.Add), name='add'),

    path('inventory/edit/<int:pk>', login_required(views.Edit), name='edit'),

    path('inventory/delete', login_required(views.Delete), name='delete'),

]

Rate/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'rate'

urlpatterns = [
    path('rate', login_required(views.Home), name='home'),

    path('rate/add/', login_required(views.Add), name='add'),

    path('rate/edit/<int:pk>', login_required(views.Edit), name='edit'),

    path('rate/delete', login_required(views.Delete), name='delete'),

]

Expense/models.py
from os import name
from django.db import models

# Create your models here.

class ExpenseType(models.Model):
    name                = models.CharField(verbose_name="Expense Type",max_length=50)
    created_at  		= models.DateField(auto_now_add=True)
    updated_at  		= models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    


class Expense(models.Model):
    type                = models.ForeignKey(ExpenseType, on_delete=models.CASCADE, null=True, blank=True)
    name                = models.CharField(verbose_name="Expense name",max_length=50, null=True, blank=True)
    description         = models.TextField(max_length=1000, null=True, blank=True)
    amount				= models.DecimalField(max_digits=13, decimal_places=2)
    created_at  		= models.DateField(verbose_name="Date")
    updated_at  		= models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return self.name if self.name else self.type.name

Expense/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Expense, ExpenseType
from django import forms

class create_form(ModelForm):
    class Meta:
        model = Expense
        fields = "__all__"

        widgets = {
        'created_at': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(create_form, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'style': 'color: white',
        })



class expense_type(ModelForm):
    class Meta:
        model = ExpenseType
        fields = "__all__"

        

    def __init__(self, *args, **kwargs):
        super(expense_type, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'style': 'color: white',
        })

Expense/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import ListView, CreateView
from .models import Expense
from .forms import create_form, expense_type
from django.urls import reverse
from django.db.models import Sum
from django.contrib import messages
from account.decorators import allowed_users

# Create your views here.


# Inventory
def Home(request):
    total_expense = Expense.objects.all().aggregate(Sum('amount'))
    context = {
        'object_list' : Expense.objects.all(),
        'total' : total_expense['amount__sum']
    }
    # salaryobj = Salary.objects.filter(employee=emp_id,created_at__month=today.month).aggregate(Sum('amount'))
    return render(request, 'expense.html', context)


def Add(request):
    form = create_form(request.POST or None)

    if form.is_valid():
        form.save()
        messages.error(request, 'Your actions have been succesfully saved !')
        return HttpResponseRedirect(reverse('expense:home'))

        
    return render(request, 'expense-add.html', {'form': form})


@allowed_users(allowed_roles=['Administrator'])
def Edit(request, pk):
    object = Expense.objects.get(id=pk)
    form = create_form(request.POST or None, instance=object)

    if form.is_valid():
        form.save()
        request.session['message'] = True
        return HttpResponseRedirect(reverse('expense:home'))
    
    return render(request, 'expense-edit.html', {'form': form})


@allowed_users(allowed_roles=['Administrator'])
def Delete(request):
    pk = request.POST['product']
    object = Expense.objects.get(id=pk)
    object.delete()
    messages.error(request, 'Your actions have been succesfully saved !')
    return HttpResponseRedirect(reverse('expense:home'))



def expense_type_add(request):
    form = expense_type(request.POST or None)

    if form.is_valid():
        form.save()
        messages.error(request, 'Your actions have been succesfully saved !')
        return HttpResponseRedirect(reverse('expense:home'))

        
    return render(request, 'expense-type-add.html', {'form': form})

Expense/templates/expense-add.html
{% extends 'base.html' %}




{% block content %}
<div class="page-header">
    <h3 class="page-title"> Expenses </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'inventory:home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page"> category </li>
      </ol>
    </nav>
</div>

{% include 'snippets/form.html' %}


{% endblock %}

Expense/templates/expense-edit.html
{% extends 'base.html' %}



{% block content %}
<div class="page-header">
    <h3 class="page-title"> Category </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'inventory:home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page"> category </li>
      </ol>
    </nav>
</div>

<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
    <div class="card-header">
        <h3> New Entry </h3>
    </div>
      <div class="card-body">
          
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}

              <div class="form-group">
                <div class="row">
                  <div class="col-md-6">
                    {{ field.label }}
                    {{ field }}

                  </div>
                </div>
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary"> Save </button>
          </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}

Expense/templates/expense-type-add.html
{% extends 'base.html' %}




{% block content %}
<div class="page-header">
    <h3 class="page-title"> Expenses </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'inventory:home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page"> category </li>
      </ol>
    </nav>
</div>

{% include 'snippets/form.html' %}

{% endblock %}

Expense/templates/expense.html
{% extends 'base.html' %}
{% load humanize %}
{% block css %}
<link rel="stylesheet" href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />
{% endblock %}

{% block js %}
<script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

<script>
  $(document).ready( function () {
    $('#myTable').DataTable({
      "order": []
    });
} );
</script>
{% endblock %}
{% block content %}
<div class="page-header">
    <h3 class="page-title"> Expense </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'expense:home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page"> expense </li>
      </ol>
    </nav>
    {% if messages %}
    {% for message in messages %}
    <div id="success-alert" class="alert alert-info">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
      <li> {{ message }} </li>
    </div>
    {% endfor %}
    {% endif %}
</div>

<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
    <div class="card-header">
        <a href="{% url 'expense:add' %}" class="btn btn-dark"> <i class="fas fa-plus"></i> New Entry </a>

        <a href="{% url 'expense:type-add' %}" class="btn btn-dark"> <i class="fas fa-plus"></i> Expense Type </a>
        
    </div>
      <div class="card-body">

        <div class="table-responsive">
          <table id="myTable" class="table">
            <thead>
              <tr>
                <th style="color: white"> Date </th>

                <th style="color: white"> Expense </th>
                <!-- <th> Products </th> -->
                <th style="color: white"> Description </th>

                <th style="color: white"> Amount </th>

                <th style="color: white"> Action </th>

              </tr>
            </thead>
            <tbody>
                {% for obj in object_list %}
              <tr>
                <td> {{ obj.created_at }} </td>
                <td>
                   {% if obj.type %} 
                   {{ obj.type.name }} - {{ obj.name }}
                   {% else %}
                   {{ obj.name }}
                   {% endif %}
                  </td>
                <td> {{ obj.description }} </td>
                <td> {{ obj.amount|intcomma }} </td>
                <td> 
                  <a style="margin: 0px 20px;" href="{% url 'expense:edit' obj.id %}">
                    <span>
                      <i class="far fa-2x fa-edit"></i>
                    </span>
                  </a>
                  <a>
                    <span id="delete_product" data-id="{{ obj.id }}" data-toggle="modal" class="delete-product text-danger" data-target="#exampleModalCenter">
                      <i class="fa fa-2x fa-trash" aria-hidden="true"></i>
                    </span>
                  </a>
                </td>
              </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 grid-margin stretch-card">
    <div class="card p-3">
      <label> Total Expenses - {{ total|intcomma }} </label>
    </div>
  </div>
</div>
<!-- Delete Dialog Confirm -->
<div class="modal  fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <form method="post" action="{% url 'expense:delete' %}">
        {% csrf_token %}
        <div style="display: none;">
          <input id="confirm_delete_product" type="text" name="product" value="" />
        </div>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"> Confirm Action </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this item from the database? <small>this action cannot be undone.</small>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}