Inventory/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'inventory'

urlpatterns = [
    path('inventory', login_required(views.Home), name='home'),

    path('inventory/add/', login_required(views.Add), name='add'),

    path('inventory/edit/<int:pk>', login_required(views.Edit), name='edit'),

    path('inventory/delete', login_required(views.Delete), name='delete'),

]

Product/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'product'

urlpatterns = [
    path('product', login_required(views.Home), name='home'),

    path('product/add/', login_required(views.Add), name='add'),

    path('product/edit/<int:pk>', login_required(views.Edit), name='edit'),

    path('product/delete', login_required(views.Delete), name='delete'),

]

Rate/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'rate'

urlpatterns = [
    path('rate', login_required(views.Home), name='home'),

    path('rate/add/', login_required(views.Add), name='add'),

    path('rate/edit/<int:pk>', login_required(views.Edit), name='edit'),

    path('rate/delete', login_required(views.Delete), name='delete'),

]

Salary/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'salary'

urlpatterns = [
    path('salary', login_required(views.Home), name='home'),

    path('salary/add/', login_required(views.Add), name='add'),

    path('salary/edit/<int:pk>', login_required(views.Edit), name='edit'),

    path('salary/delete', login_required(views.Delete), name='delete'),

]

Rate/models.py
from django.db import models

# Create your models here.

class Rate(models.Model):
    local_currency      = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    dollars             = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    rate                = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    created_at  		= models.DateField(verbose_name="Date")








    

Rate/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Rate
from django import forms


class create_form(ModelForm):
    class Meta:
        model = Rate
        exclude = ('dollars',)

        widgets = {
        'created_at': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(create_form, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'style': 'color: white',
        })

Rate/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import ListView, CreateView
from .models import Rate
from .forms import create_form
from django.urls import reverse
from django.db.models import Sum
from django.contrib import messages
from account.decorators import allowed_users
# Create your views here.


# rate
def Home(request):
    local = Rate.objects.all().aggregate(Sum('local_currency'))
    dollars = Rate.objects.all().aggregate(Sum('dollars'))
    
    context = {
        'object_list' : Rate.objects.all(),
        'local' : local['local_currency__sum'],
        'dollars' : dollars['dollars__sum'],
    }
    return render(request, 'rate.html', context)


def Add(request):
    form = create_form(request.POST or None)

    if form.is_valid():
        form = form.save(commit=True)
        dollars = form.local_currency / form.rate
        form.dollars = dollars
        form.save()
        messages.error(request, 'Your actions have been succesfully saved !')
        return HttpResponseRedirect(reverse('rate:home'))

        
    return render(request, 'rate-add.html', {'form': form})


@allowed_users(allowed_roles=['Administrator'])
def Edit(request, pk):
    object = Rate.objects.get(id=pk)
    form = create_form(request.POST or None, instance=object)

    if form.is_valid():
        form = form.save(commit=True)
        dollars = form.local_currency / form.rate
        form.dollars = dollars
        form.save()
        messages.error(request, 'Your actions have been succesfully saved !')
        return HttpResponseRedirect(reverse('rate:home'))
    
    return render(request, 'rate-edit.html', {'form': form})


@allowed_users(allowed_roles=['Administrator'])
def Delete(request):
    pk = request.POST['product']
    object = Rate.objects.get(id=pk)
    object.delete()
    messages.error(request, 'Your actions have been succesfully saved !')
    return HttpResponseRedirect(reverse('rate:home'))

Rate/templates/rate-add.html
{% extends 'base.html' %}




{% block content %}
<div class="page-header">
    <h3 class="page-title"> Category </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'inventory:home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page"> category </li>
      </ol>
    </nav>
</div>

<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
    <div class="card-header">
        <h3> New Entry </h3>
    </div>
      <div class="card-body">
        {% if credit == 0 %}
        <div class="alert alert-danger">
          <h3> There is no enough Salary for the selected employee! </h3>
        </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}

              <div class="form-group">
                <div class="row">
                  <div class="col-md-6">
                    {{ field.label }}
                    {{ field }}
                    {{ field.errors }}

                  </div>
                </div>
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary"> Save </button>
          </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}

Rate/templates/rate-edit.html
{% extends 'base.html' %}



{% block content %}
<div class="page-header">
    <h3 class="page-title"> Category </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'product:home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page"> category </li>
      </ol>
    </nav>
</div>

<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
    <div class="card-header">
        <h3> New Entry </h3>
    </div>
      <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}

              <div class="form-group">
                <div class="row">
                  <div class="col-md-6">
                    {{ field.label }}
                    {{ field }}

                  </div>
                </div>
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary"> Save </button>
          </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}

Rate/templates/rate.html
{% extends 'base.html' %}
{% load humanize %}

{% block css %}
<link rel="stylesheet" href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />
{% endblock %}

{% block js %}
<script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

<script>
  $(document).ready( function () {
    $('#myTable').DataTable({
      "order": []
    });
} );
</script>
{% endblock %}

{% block content %}
<div class="page-header">
    <h3 class="page-title"> Rate </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'salary:home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page"> rate </li>
      </ol>
    </nav>
    {% if messages %}
    {% for message in messages %}
    <div id="success-alert" class="alert alert-info">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
      <li> {{ message }} </li>
    </div>
    {% endfor %}
    {% endif %}
</div>

<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
    <div class="card-header">
        <a href="{% url 'rate:add' %}" class="btn btn-dark"> <i class="fas fa-plus"></i>New Entry </a>
        
    </div>
      <div class="card-body">

        <div class="table-responsive">
          <table id="myTable" class="table">
            <thead>
              <tr>
                <th> Date </th>

                <th> local </th>

                <th> rate </th>

                <th> Dollars </th>

                <th> Action </th>

              </tr>
            </thead>
            <tbody>
                {% for obj in object_list %}
              <tr>
                <td> {{ obj.created_at }} </td>
                <td> {{ obj.local_currency|intcomma }} </td>
                <td> {{ obj.rate|intcomma }} </td>
                <td> {{ obj.dollars }} </td>
                
                <td> 
                  <a style="margin: 0px 20px;" href="{% url 'rate:edit' obj.id %}">
                    <span>
                      <i class="far fa-2x fa-edit"></i>
                    </span>
                  </a>
                  <a>
                    <span id="delete_product" data-id="{{ obj.id }}" data-toggle="modal" class="delete-product text-danger" data-target="#exampleModalCenter">
                      <i class="fa fa-2x fa-trash" aria-hidden="true"></i>
                    </span>
                  </a>
                </td>
              </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 grid-margin stretch-card">
    <div class="card p-3">
      <label> Total Local - {{ local|intcomma }} </label>
      <label> Total Dollars - {{ dollars|intcomma }} </label>
    </div>
  </div>
</div>


<!-- Delete Dialog Confirm -->
<div class="modal  fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <form method="post" action="{% url 'rate:delete' %}">
        {% csrf_token %}
        <div style="display: none;">
          <input id="confirm_delete_product" type="text" name="product" value="" />
        </div>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"> Confirm Action </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this item from the database? <small>this action cannot be undone.</small>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}